#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Answers issue #17 on the wayfinder map (birdman7260/homeserver#1): what is
# actually running on the Qidi Plus 4, what Moonraker really trusts, and
# whether the default logins still work.
#
# Everything here READS except the last stage, which changes a default
# password if one still works. Nothing is installed on the printer, no
# service is started or stopped, and no config is edited.
#
# Run this from a machine on the same network as the printer.

REPORT="${REPORT:-/tmp/qidi-inspection-$(date +%Y%m%d-%H%M).txt}"
{
  printf 'Qidi Plus 4 inspection\n'
  printf 'Ticket: https://github.com/birdman7260/homeserver/issues/17\n'
  printf 'Run at: %s\n' "$(date '+%Y-%m-%d %H:%M %Z')"
} > "$REPORT"

# Remembered answers live outside the repo: this one is public, and a stray
# .env in a clone is how a private address leaks into a commit.
ENV_FILE="${ENV_FILE:-/tmp/qidi-inspection.env}"

PRINTER_IP=""
SSH_SOCK=""
SSH_READY=0

# report_header "Label" starts a section in the report.
report_header() { printf '\n===== %s =====\n' "$1" >> "$REPORT"; }

# note_report "Label" "text" records a human-supplied answer.
note_report() {
  report_header "$1"
  printf '%s\n' "$2" >> "$REPORT"
  printf '  %s✓%s recorded: %s\n' "$GREEN" "$RESET" "$1"
}

# probe "Label" -- cmd args...  runs a read-only command HERE (not on the
# printer) and appends its output. Never fails the run.
probe() {
  local label="$1"; shift
  if [[ "${1:-}" == "--" ]]; then shift; fi
  {
    report_header "$label"
    printf '$ %s\n' "$*"
    if command -v "$1" >/dev/null 2>&1; then
      "$@" 2>&1 || printf '(command exited %s)\n' "$?"
    else
      printf '(not installed: %s)\n' "$1"
    fi
  } >> "$REPORT"
  printf '  %s·%s %s\n' "$DIM" "$RESET" "$label"
}

# remote "Label" 'shell command'  runs a read-only command ON THE PRINTER over
# the shared SSH connection and appends its output.
remote() {
  local label="$1" cmd="$2"
  {
    report_header "$label"
    printf '$ %s\n' "$cmd"
    if (( SSH_READY )); then
      ssh -S "$SSH_SOCK" "mks@$PRINTER_IP" "$cmd" 2>&1 || printf '(command exited %s)\n' "$?"
    else
      printf '(no SSH session)\n'
    fi
  } >> "$REPORT"
  printf '  %s·%s %s\n' "$DIM" "$RESET" "$label"
}

# port_open IP PORT: true if something is listening. macOS netcat spells the
# connect timeout -G; the openbsd netcat on Linux has no such flag and would
# fail every probe if given one, reading as "everything is closed".
port_open() {
  if command -v nc >/dev/null 2>&1; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
      nc -z -G 2 -w 2 "$1" "$2" >/dev/null 2>&1
    else
      nc -z -w 2 "$1" "$2" >/dev/null 2>&1
    fi
  else
    # bash's own /dev/tcp, where nc is missing. No timeout of its own, so a
    # filtered port waits on the kernel's.
    (exec 3<>"/dev/tcp/$1/$2") >/dev/null 2>&1
  fi
}

# close_ssh tears the shared connection down on exit, however we leave.
close_ssh() {
  [[ -n "$SSH_SOCK" && -S "$SSH_SOCK" ]] || return 0
  ssh -S "$SSH_SOCK" -O exit "mks@$PRINTER_IP" >/dev/null 2>&1 || true
}
trap close_ssh EXIT

banner "Qidi Plus 4 inspection (read-only)"

# ── 1. Find the printer ───────────────────────────────────────────────────
stage "Find the printer on the network"
say "Everything collects into one file you can paste back into issue #17:"
note "  $REPORT"
printf '\n'
warn "Run this from a machine on the SAME network as the printer, and make"
warn "sure the printer is powered on and past its splash screen."
printf '\n'

ask PRINTER_IP "Printer IP address (Enter to scan for it):"

if [[ -z "$PRINTER_IP" ]]; then
  # This machine's address on whichever interface carries the default route,
  # which is not always en0 on a laptop with Ethernet or a dock.
  MY_IF=$(route -n get default 2>/dev/null | awk '/interface:/{print $2}' || true)
  MY_IP=$(ipconfig getifaddr "${MY_IF:-en0}" 2>/dev/null || true)
  if [[ -z "$MY_IP" ]]; then
    MY_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
  fi
  if [[ -z "$MY_IP" ]]; then
    warn "couldn't work out this machine's address; enter the printer's IP by hand"
    ask PRINTER_IP "Printer IP address:"
  else
    SUBNET="${MY_IP%.*}"
    say "Scanning $SUBNET.0/24 for Moonraker on port 7125. Takes about 15s."
    FOUND=""
    for i in $(seq 1 254); do
      ( port_open "$SUBNET.$i" 7125 && echo "$SUBNET.$i" >> "$REPORT.scan" ) &
    done
    wait
    [[ -f "$REPORT.scan" ]] && FOUND=$(sort -u "$REPORT.scan" | tr '\n' ' ')
    rm -f "$REPORT.scan"
    if [[ -n "$FOUND" ]]; then
      say "Answering on 7125: $FOUND"
      ask PRINTER_IP "Which one is the printer?"
    else
      warn "nothing answered on 7125. The printer may be off, on Wi-Fi while this"
      warn "machine is on a different VLAN, or Moonraker may not be listening."
      ask PRINTER_IP "Printer IP address (blank to give up):"
    fi
  fi
fi

if [[ -z "$PRINTER_IP" ]]; then
  warn "No printer address: stopping here. Re-run when you can reach it."
  exit 1
fi

write_env QIDI_IP "$PRINTER_IP"
note_report "Printer IP" "$PRINTER_IP"
probe "ping" -- ping -c 3 "$PRINTER_IP"

# ── 2. The touchscreen: firmware and LAN-only mode ────────────────────────
stage "Touchscreen: firmware version and LAN-only mode"
say "Qidi has published no source after V1.7.1, so the version decides how much"
say "of the research still applies. Only the screen can tell you."
printf '\n'
step "On the printer: Settings → About (or System Info). Read the firmware version."
step "Then: Settings → Network. Find the LAN-only mode switch and note on or off."
printf '\n'
note "If LAN-only is OFF, the vendor cloud client may be running. Leave the"
note "switch exactly as you find it — this stage only reads."
printf '\n'
FW=""; LANONLY=""
ask FW "Firmware version shown on screen:"
ask LANONLY "LAN-only mode (on / off / not found):"
note_report "Firmware version (touchscreen)" "${FW:-unanswered}"
note_report "LAN-only mode (touchscreen)" "${LANONLY:-unanswered}"

# ── 3. The router: does the address stay put? ─────────────────────────────
stage "Router: DHCP reservation for the printer"
say "A Tailscale subnet route points at a fixed address. If the printer's"
say "lease can move, the route breaks the next time the power blinks."
printf '\n'
step "Open the router admin page and find its DHCP reservation / static lease list."
step "Look for $PRINTER_IP, or the printer by name."
printf '\n'
RESERVED=""
ask RESERVED "Is there a reservation for the printer? (yes / no / unsure):"
note_report "DHCP reservation" "${RESERVED:-unanswered} (address $PRINTER_IP)"
if [[ "$RESERVED" =~ ^[Nn] ]]; then
  note "Not a problem to fix now — the access ticket will ask for one."
fi

# ── 4. What another machine sees, with no login ───────────────────────────
stage "Unauthenticated: what this machine can reach without credentials"
say "This is the heart of the ticket. Moonraker reports whether it trusts the"
say "caller, and the camera either needs a login or it doesn't."
printf '\n'
for p in 22 80 443 7125 8080; do
  if port_open "$PRINTER_IP" "$p"; then
    printf '  %s·%s port %s open\n' "$DIM" "$RESET" "$p"
    printf '\n===== port %s =====\nopen\n' "$p" >> "$REPORT"
  else
    printf '  %s·%s port %s closed or filtered\n' "$DIM" "$RESET" "$p"
    printf '\n===== port %s =====\nclosed or filtered\n' "$p" >> "$REPORT"
  fi
done

probe "access/info (does Moonraker trust this machine?)" \
  -- curl -sS -m 10 "http://$PRINTER_IP:7125/access/info"
probe "server/info (Moonraker version and components)" \
  -- curl -sS -m 10 "http://$PRINTER_IP:7125/server/info"
probe "printer/info (Klipper version and state)" \
  -- curl -sS -m 10 "http://$PRINTER_IP:7125/printer/info"
probe "machine/system_info (host, distro, service list)" \
  -- curl -sS -m 10 "http://$PRINTER_IP:7125/machine/system_info"

say ""
say "Now the header test. The published fork trusts any caller claiming to be"
say "127.0.0.1 in an X-Real-Ip header, before it checks logins at all. The"
say "research inferred that from source and never tested it on hardware."
probe "access/info with a spoofed X-Real-Ip (the header bypass)" \
  -- curl -sS -m 10 -H "X-Real-Ip: 127.0.0.1" "http://$PRINTER_IP:7125/access/info"

probe "camera snapshot headers (port 8080, no login)" \
  -- curl -sS -m 10 -o /dev/null -D - "http://$PRINTER_IP:8080/?action=snapshot"
probe "camera snapshot through nginx (port 80)" \
  -- curl -sS -m 10 -o /dev/null -D - "http://$PRINTER_IP/webcam/?action=snapshot"
probe "web UI headers (port 80)" \
  -- curl -sS -m 10 -o /dev/null -D - "http://$PRINTER_IP/"

pause "Collected. Press Enter to log in over SSH."

# ── 5. SSH: the default login, and what Moonraker really trusts ───────────
stage "SSH: default login, and the real config"
say "Qidi documents the default login as mks / makerbase. The community says"
say "root takes the same password. Both claims get tested here."
printf '\n'
note "You'll be asked for the password once; the wizard reuses that one"
note "connection for every command. The password is never written down."
printf '\n'
step "If it asks about the host's authenticity, that's normal on a first"
step "  connection to a device you've never SSH'd into. Answer yes."
printf '\n'

SSH_SOCK="${TMPDIR:-/tmp}/qidi-ssh-$$"
DEFAULT_WORKED=""
if ssh -M -S "$SSH_SOCK" -f -N \
     -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 \
     "mks@$PRINTER_IP" 2>&1; then
  SSH_READY=1
  printf '\n  %s✓%s connected as mks\n\n' "$GREEN" "$RESET"
  ask DEFAULT_WORKED "Did the documented default password (makerbase) work? (yes / no):"
else
  warn "couldn't open an SSH session. Recording that and carrying on."
  note_report "SSH as mks" "failed to connect"
  ask DEFAULT_WORKED "Did you get as far as a password prompt? (yes / no / unsure):"
fi
note_report "Default login mks/makerbase" "${DEFAULT_WORKED:-unanswered}"

if (( SSH_READY )); then
  remote "moonraker.conf (the real [authorization] block)" \
    'cat ~/printer_data/config/moonraker.conf'
  remote "QIDILink-client: enabled?"  'systemctl is-enabled QIDILink-client 2>&1'
  remote "QIDILink-client: active?"   'systemctl is-active QIDILink-client 2>&1'
  remote "QIDILink-client: unit"      'systemctl status QIDILink-client --no-pager 2>&1 | head -20'
  remote "firmware / release markers" 'cat /boot/*version* /etc/qidi* /root/xindi/version* 2>/dev/null; ls /root 2>/dev/null'
  remote "OS release"                 'cat /etc/os-release'
  remote "kernel"                     'uname -a'
  remote "listening ports (the QIDILink port among them)" \
    'ss -tulpn 2>/dev/null || netstat -tulpn 2>/dev/null'
  remote "running services"           'systemctl list-units --type=service --state=running --no-pager'
  remote "nginx: does it pass the real client IP to Moonraker?" \
    'grep -rn -e real_ip -e X-Real-Ip -e proxy_set_header /etc/nginx 2>/dev/null'
  remote "Tornado version (decides whether xheaders applies)" \
    '~/moonraker-env/bin/python -c "import tornado; print(tornado.version)" 2>&1'
  remote "camera config"              'cat ~/printer_data/config/webcam.txt 2>/dev/null; cat /boot/webcam.txt 2>/dev/null'
  remote "Fluidd version"             'cat ~/fluidd/.version 2>/dev/null; ls ~/fluidd 2>/dev/null | head'
  remote "Moonraker users (does any login exist?)" \
    'ls -l ~/printer_data/moonraker.secrets ~/printer_data/database 2>/dev/null'
  pause "Collected. Press Enter for the root check."
fi

# ── 6. Does root take the same password? ──────────────────────────────────
stage "Root: the undocumented default"
say "The community claims root logs in directly with the same password. Qidi"
say "does not document this. If it's true, it's the most exposed thing here."
printf '\n'
step "In another terminal, or right here after this wizard:  ssh root@$PRINTER_IP"
step "Try the same password. Don't change anything if you get in — just note it."
printf '\n'
ROOT_LOGIN=""
ask ROOT_LOGIN "Does root accept the same password? (yes / no / untested):"
note_report "Root login with the default password" "${ROOT_LOGIN:-unanswered}"

# ── 7. Change the default, if it still works ──────────────────────────────
stage "Change the default password"
if [[ "$DEFAULT_WORKED" =~ ^[Yy] || "$ROOT_LOGIN" =~ ^[Yy] ]]; then
  warn "A default password on a device that gives any LAN client full control"
  warn "of heaters and motion is the one thing worth fixing before you leave."
  printf '\n'
  step "Generate a password in Bitwarden first, so it exists somewhere before"
  step "  it exists on the printer."
  step "Then:  ssh mks@$PRINTER_IP  and run:  passwd"
  step "If root also logs in, do the same there:  ssh root@$PRINTER_IP  then  passwd"
  printf '\n'
  note "Store it as an operational secret in Bitwarden Secrets Manager — it is"
  note "machine-facing and rotatable, not something anyone inherits."
  note "See docs/secrets.md for why that home and not the individual vault."
  printf '\n'
  warn "Never paste the password into the report, this issue, or the repo."
  printf '\n'
  CHANGED=""
  ask CHANGED "Which accounts did you change? (mks / root / both / none yet):"
  note_report "Default passwords changed" "${CHANGED:-unanswered}"
  if [[ ! "$CHANGED" =~ ^[Nn] ]]; then
    note_report "Where the new password lives" \
      "Bitwarden Secrets Manager (confirm, then add a row to docs/secrets.md)"
  fi
else
  say "The defaults didn't work, so there's nothing to change."
  say "Record how you do log in, so the secrets registry can account for it."
  WHERE=""
  ask WHERE "Where is the working SSH password kept today?"
  note_report "Existing SSH credential" "${WHERE:-unanswered}"
fi

# ──────────────────────────────────────────────────────────────────────────

close_ssh
_clear
printf '\n%s%s  ✓ Inspection complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
note "Report written to: $REPORT"
printf '\n'
warn "Skim it before sharing. 'ss -tulpn', the Moonraker config and the system_info"
warn "response can carry hostnames, MAC addresses and occasionally a token. The"
warn "printer's LAN address is fine to post; anything that looks like a key is not."
printf '\n'
say "Send it back with whichever is easiest:"
note "  cat $REPORT                                # then copy-paste"
note "  gh issue comment 17 --body-file $REPORT    # straight onto the ticket"
printf '\n'
