#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# This wizard only READS. It installs nothing, starts nothing, stops nothing,
# and writes only to its own report file under /tmp. Answers issue #2 on the
# wayfinder map (birdman7260/homeserver#1).

REPORT="${REPORT:-/tmp/nuc-inventory-$(date +%Y%m%d-%H%M).txt}"
: > "$REPORT"

# collect "Label" -- cmd args...   runs a read-only command, appends its output
# to the report under a header, and never fails the run when the tool is absent.
collect() {
  local label="$1"; shift
  if [[ "${1:-}" == "--" ]]; then shift; fi
  {
    printf '\n===== %s =====\n' "$label"
    printf '$ %s\n' "$*"
    if command -v "${1}" >/dev/null 2>&1 || [[ "$1" == "sudo" ]]; then
      "$@" 2>&1 || printf '(command exited %s)\n' "$?"
    else
      printf '(not installed: %s)\n' "$1"
    fi
  } >> "$REPORT"
  printf '  %s·%s %s\n' "$DIM" "$RESET" "$label"
}

# note_report "..." records a human-supplied answer in the report.
note_report() { printf '\n===== %s =====\n%s\n' "$1" "$2" >> "$REPORT"; }

banner "NUC inventory (read-only)"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Preflight: sudo and report file"
say "Everything this wizard runs is read-only. Nothing is installed or changed."
say "Output collects into a single file you can paste back:"
note "  $REPORT"
printf '\n'
step "Several commands need sudo (dmidecode, nvme, smartctl, virsh)."
step "Authenticate once now so later stages don't stop to ask."
sudo -v || warn "sudo failed; hardware stages will be thin but the rest still works"
collect "date / uptime" -- uptime
collect "os-release" -- cat /etc/os-release
collect "kernel" -- uname -a

# ── 2. Hardware, BIOS, memory slots ───────────────────────────────────────
stage "Hardware: board, BIOS, CPU, memory slots"
say "Confirming the exact NUC model, and whether RAM has room to grow."
collect "dmidecode: system + baseboard" -- sudo dmidecode -t system -t baseboard
collect "dmidecode: BIOS" -- sudo dmidecode -t bios
collect "lscpu" -- lscpu
collect "free -h" -- free -h
collect "dmidecode: memory (slots, sizes, max capacity)" -- sudo dmidecode -t memory
collect "boot mode (UEFI if this directory exists)" -- ls /sys/firmware/efi
pause "Collected. Press Enter for storage."

# ── 3. Storage, partitions, SSD wear ──────────────────────────────────────
stage "Storage: drives, partitions, and how worn the SSD is"
say "The boot SSD's wear level decides whether it is trustworthy as a rollback."
collect "lsblk" -- lsblk -o NAME,SIZE,MODEL,SERIAL,TRAN,ROTA,FSTYPE,MOUNTPOINT
collect "nvme list" -- sudo nvme list
collect "nvme controllers present" -- ls -l /sys/class/nvme
collect "partitions" -- sudo parted -l
collect "disk usage" -- df -hT
for dev in /dev/nvme0n1 /dev/nvme1n1 /dev/sda /dev/sdb; do
  [[ -e "$dev" ]] && collect "SMART health: $dev" -- sudo smartctl -a "$dev"
done
pause "Collected. Press Enter for virtualisation."

# ── 4. Virtualisation and what else runs on the host ──────────────────────
stage "Virtualisation: the Home Assistant VM and host services"
say "Anything running on the host that isn't the HA VM would be lost in a wipe."
collect "virsh: all VMs" -- sudo virsh list --all
if command -v virsh >/dev/null 2>&1; then
  for vm in $(sudo virsh list --all --name 2>/dev/null); do
    [[ -n "$vm" ]] || continue
    collect "virsh dumpxml: $vm" -- sudo virsh dumpxml "$vm"
    collect "virsh dominfo: $vm" -- sudo virsh dominfo "$vm"
  done
fi
collect "libvirt disk images" -- sudo ls -lh /var/lib/libvirt/images
collect "VirtualBox VMs (if used instead)" -- VBoxManage list vms
collect "docker containers (HA may run here)" -- sudo docker ps -a
collect "running services" -- systemctl list-units --type=service --state=running --no-pager
collect "enabled services" -- systemctl list-unit-files --state=enabled --no-pager
collect "listening ports" -- sudo ss -tulpn
collect "root crontab" -- sudo crontab -l
collect "user crontab" -- crontab -l
pause "Collected. Press Enter for USB devices."

# ── 5. USB radios: the classic migration casualty ─────────────────────────
stage "USB: Zigbee / Z-Wave radios passed through to the VM"
say "These need passthrough reconfigured on Proxmox. Miss one and half the"
say "house goes dead while the migration still looks successful."
collect "lsusb" -- lsusb
collect "serial devices by-id (Zigbee/Z-Wave sticks appear here)" -- ls -l /dev/serial/by-id
collect "ttyUSB / ttyACM devices" -- ls -l /dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyACM0 /dev/ttyACM1
pause "Collected. Press Enter for network."

# ── 6. Network ────────────────────────────────────────────────────────────
stage "Network: addressing and how it is assigned"
say "Static or DHCP reservation decides what has to be recreated after the move."
collect "addresses" -- ip -brief addr
collect "routes" -- ip route
collect "DNS" -- cat /etc/resolv.conf
collect "NetworkManager connections" -- nmcli -t connection show
collect "netplan config" -- sudo sh -c 'cat /etc/netplan/*.yaml'
collect "interfaces file" -- cat /etc/network/interfaces
pause "Collected. One manual step left."

# ── 7. The physical M.2 question ──────────────────────────────────────────
stage "Physical: confirm the M.2 slot situation"
warn "This is the step that decides which drive to buy, so it is worth the screwdriver."
printf '\n'
say "Intel's spec for the NUC8BE board says the BEK (slim) chassis has exactly"
say "ONE storage M.2 slot (22x42 or 22x80, M-key, SATA or PCIe x4 NVMe) and no"
say "2.5\" bay. If that holds, there is no free slot for a second drive and the"
say "plan changes from 'add a drive' to 'swap the drive, keep the old one'."
printf '\n'
step "Power off, unplug, undo the four corner screws, lift the base plate off."
step "Look at the board: the WiFi card sits in a small 2230 E-key slot. That one"
step "  cannot take an SSD. Look for any OTHER M.2 slot beside the populated one."
step "Photograph the board before closing it up: it saves a second teardown."
printf '\n'
SECOND_SLOT=""
ask SECOND_SLOT "Is there a second FREE storage M.2 slot? (yes / no / unsure):"
note_report "Physical inspection: second free storage M.2 slot?" "${SECOND_SLOT:-unanswered}"
CHASSIS=""
ask CHASSIS "Chassis height: slim (BEK, ~35mm) or tall (BEH, ~51mm)?"
note_report "Chassis" "${CHASSIS:-unanswered}"

# ──────────────────────────────────────────────────────────────────────────

_clear
printf '\n%s%s  ✓ Inventory complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
note "Report written to: $REPORT"
printf '\n'
warn "Skim it before sharing: 'ss -tulpn' and the VM XML can expose hostnames,"
warn "MAC addresses and occasionally a token. Redact anything you'd rather not"
warn "post to a GitHub issue."
printf '\n'
say "Send it back with whichever is easiest:"
note "  cat $REPORT                       # then copy-paste"
note "  gh issue comment 2 --body-file $REPORT   # if gh is on this box"
note "  scp $(whoami)@$(hostname):$REPORT .   # pull it from your laptop"
printf '\n'
