#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Turns issue #20 on the wayfinder map (birdman7260/homeserver#1) from a
# design into a fact: the succession layer decided in #7 and recorded in
# ADR-0001, actually standing up in Bitwarden.
#
# THIS WIZARD CAPTURES NO SECRET VALUES. It asks whether a credential exists,
# never what it is. #19 burned two ESPHome secrets purely by having them in a
# transcript; a succession master password would be unrecoverable from that.
# If a stage ever seems to want a password, a seed or a recovery code, it has
# been misread — the answer is always yes or no.
#
# Everything it writes lands outside this repository, which is public.

REPORT="${REPORT:-${TMPDIR:-/tmp}/succession-$(date +%Y%m%d-%H%M).txt}"
INDEX_NOTE="${INDEX_NOTE:-${TMPDIR:-/tmp}/index-note-$(date +%Y%m%d-%H%M).md}"
ENV_FILE="${ENV_FILE:-${TMPDIR:-/tmp}/succession-layer.env}"

{
  printf 'Succession layer standup\n'
  printf 'Ticket: https://github.com/birdman7260/homeserver/issues/20\n'
  printf 'Run at: %s\n' "$(date '+%Y-%m-%d %H:%M %Z')"
} > "$REPORT"

OUTSTANDING=()   # checklist lines that did not get ticked this run

VAULT_URL="https://vault.bitwarden.com/#/settings/emergency-access"

report_header() { printf '\n===== %s =====\n' "$1" >> "$REPORT"; }

# record "Label" "text" files a human-supplied answer in the report.
record() {
  report_header "$1"
  printf '%s\n' "$2" >> "$REPORT"
  printf '  %s✓%s recorded: %s\n' "$GREEN" "$RESET" "$1"
}

# tick "checklist line" "question"  is the unit this ticket is made of: a box
# that is either genuinely ticked or genuinely outstanding. Anything not
# ticked is carried to the closing summary rather than quietly forgotten,
# because a half-done succession layer that reads as done is the failure this
# whole ticket exists to prevent.
tick() {
  local label="$1" question="$2"
  if confirm "$question"; then
    record "$label" "done"
  else
    record "$label" "NOT DONE"
    OUTSTANDING+=("$label")
    warn "left outstanding; it'll be in the summary at the end"
  fi
}

banner "Stand up the succession layer in Bitwarden"

say "This is the highest-value item on the map: a perfect runbook behind"
say "credentials nobody can reach is worth nothing."
printf '\n'
note "Notes collect into a file you can paste back onto issue #20:"
note "  $REPORT"
printf '\n'
warn "It will never ask you for a password, a TOTP seed or a recovery code."
warn "Only whether one exists. Nothing here should ever need rotating."
printf '\n'
pause "Understood? Press Enter."

# ── 1. Premium, and the bill nobody can find ──────────────────────────────
stage "Premium, and the bill nobody can find"
say "Emergency Access is a premium feature on the GRANTOR's account. Your"
say "brothers can be on free accounts; you cannot."
printf '\n'
warn "This is the circular failure worth designing out now: if the Bitwarden"
warn "subscription lapses, Emergency Access stops working — and the payment"
warn "details that would renew it live inside the vault nobody can now open."
printf '\n'
open_url "https://vault.bitwarden.com/#/settings/subscription"
printf '\n'
step "Confirm the subscription is active, and note its renewal date."
step "Note which card pays it, and whether that card dies with you."
printf '\n'
PREMIUM=""; RENEWS=""; CARD=""
ask PREMIUM "Is Premium active? (yes / no):"
ask RENEWS  "Renewal date shown:"
ask CARD    "What pays it, and does that account survive you? (e.g. 'joint card, survives'):"
record "Bitwarden Premium" "active: ${PREMIUM:-unanswered}; renews: ${RENEWS:-unanswered}; paid by: ${CARD:-unanswered}"
write_env BW_RENEWAL "${RENEWS:-unknown}"
if [[ ! "$PREMIUM" =~ ^[Yy] ]]; then
  warn "Without Premium there is no Emergency Access and stages 3 and 4 cannot"
  warn "be completed. Buy it now if you can; otherwise the rest still records."
  OUTSTANDING+=("Bitwarden Premium is not active — Emergency Access is unavailable")
  pause "Press Enter to carry on."
fi
note "Bitwarden itself is a load-bearing account. Stage 7 will ask you for its"
note "disposition — and the honest answer is almost certainly 'leave running'."

# ── 2. Retire 1Password from the NUC ──────────────────────────────────────
stage "Retire 1Password from the NUC"
say "The #2 inventory found a 1Password snap on the NUC's desktop. You've"
say "confirmed it is vestigial — nothing in it."
printf '\n'
warn "Two password managers is worse for a successor than either one alone:"
warn "they find the wrong one, or find both and cannot tell which is real."
warn "Remove the ambiguity while it costs one command."
printf '\n'
step "On the NUC:  snap list | grep -i 1password"
step "Then:        sudo snap remove 1password"
printf '\n'
note "The NUC's whole desktop layer is #30's problem, not this ticket's. This"
note "stage only kills the second password manager, so it can never appear in"
note "a succession story. Leave the rest of the desktop alone."
printf '\n'
OP_GONE=""
ask OP_GONE "1Password on the NUC: (removed / wasn't there / still present):"
record "1Password on the NUC" "${OP_GONE:-unanswered}"
if [[ "$OP_GONE" =~ ^[Ss] ]]; then
  OUTSTANDING+=("1Password is still installed on the NUC — remove the snap")
fi

# ── 3. Invite each brother as an emergency contact ────────────────────────
stage "Invite each brother as an emergency contact"
say "Takeover, 30-day wait. Takeover is the right level because the job is to"
say "wind the system down or keep it running, and View cannot change a"
say "password, cancel a subscription or transfer a domain."
printf '\n'
warn "Takeover REPLACES your master password and removes your two-step login"
warn "when it completes. That is the point — and it is also why 30 days of"
warn "wait, with email at every step, is the guard rail. You can deny a"
warn "request at any time before it matures."
printf '\n'
note "Each brother needs a Bitwarden account (free is fine) on the same server"
note "as yours. The invitation email walks them through creating one."
printf '\n'
open_url "$VAULT_URL"
printf '\n'
step "Settings → Emergency access → Add emergency contact"
step "Enter their email, choose Takeover, set the wait time to 30 days, Save."
step "Repeat for the second brother."
printf '\n'
B1=""; B2=""
ask B1 "First brother's Bitwarden email:"
ask B2 "Second brother's Bitwarden email (blank if only one):"
if [[ -n "$B1" ]]; then write_env SUCCESSOR_1 "$B1"; fi
if [[ -n "$B2" ]]; then write_env SUCCESSOR_2 "$B2"; fi
record "Emergency contacts invited" \
  "1: ${B1:-none}; 2: ${B2:-none}; access level Takeover; wait 30 days"
tick "Both contacts invited at Takeover / 30-day" \
     "Is the invitation sent for everyone who should have one?"

# ── 4. Chase every contact to Confirmed ───────────────────────────────────
stage "Chase every contact to Confirmed"
warn "The step the checklist was missing. Emergency Access has THREE states,"
warn "not two:"
printf '\n'
say "    Invited      → they haven't clicked the email yet"
say "    Needs confirmation → they accepted; you have not finished it"
say "    Confirmed    → the encrypted key is actually shared"
printf '\n'
warn "Only Confirmed works. A contact sitting at 'Needs confirmation' looks"
warn "present in the list and conveys nothing at all — the failure you would"
warn "discover at the worst possible moment."
printf '\n'
step "Chase them until each row reads 'Needs confirmation'."
step "Then: the ⋮ menu on the row → Confirm."
step "Bitwarden shows a fingerprint phrase. Read it to them on the PHONE and"
step "  check it matches what they see before you press Confirm."
printf '\n'
note "The phone call is not ceremony: the fingerprint is what proves you are"
note "handing the key to your brother and not to whoever controls that inbox."
printf '\n'
open_url "$VAULT_URL"
printf '\n'
S1=""; S2=""
ask S1 "Status shown for ${B1:-the first contact}: (confirmed / needs confirmation / invited):"
if [[ -n "$B2" ]]; then ask S2 "Status shown for $B2:"; fi
record "Emergency contact status" \
  "${B1:-contact 1}: ${S1:-unanswered}; ${B2:-contact 2}: ${S2:-n/a}"
if [[ ! "$S1" =~ ^[Cc] ]]; then
  OUTSTANDING+=("${B1:-contact 1} is not Confirmed — conveys nothing until it is")
fi
if [[ -n "$B2" && ! "$S2" =~ ^[Cc] ]]; then
  OUTSTANDING+=("$B2 is not Confirmed — conveys nothing until it is")
fi

# ── 5. Vault hygiene: items hiding in an organization ─────────────────────
stage "Vault hygiene: items hiding in an organization"
warn "The sharp edge in ADR-0001. Emergency Access conveys the INDIVIDUAL"
warn "vault only. Anything filed into an organization or a shared collection"
warn "is invisible to a successor — so tidying succession secrets into a neat"
warn "shared collection silently breaks inheritance while looking more"
warn "organised. Tidiness is the trap."
printf '\n'
open_url "https://vault.bitwarden.com/#/vault"
printf '\n'
step "In the vault filter down the left, click each organization in turn."
step "Read every item it holds and ask: would a successor need this to wind"
step "  the system down? Registrar, DNS, storage, billing — those must move."
step "Move each one: item → ⋮ → Move to → your individual vault."
printf '\n'
note "Machine-facing tokens are the opposite case and should NOT move. They"
note "belong in Secrets Manager, outside Emergency Access by construction: a"
note "successor needs account logins, never the keys to rebuild. docs/secrets.md"
printf '\n'
MOVED=""
ask MOVED "Which items did you move out of an organization? (or 'none found'):"
record "Organization-held items moved to the individual vault" "${MOVED:-unanswered}"
tick "Vault audited for succession items in organizations" \
     "Have you looked in every organization, not just the obvious one?"

# ── 6. TOTP seeds and 2FA recovery codes ──────────────────────────────────
stage "TOTP seeds and 2FA recovery codes"
say "A successor with your password and no second factor is locked out just"
say "as thoroughly as a successor with nothing."
printf '\n'
warn "Check the phone-only case specifically: any account whose second factor"
warn "is an authenticator app on YOUR phone, with the recovery codes nowhere"
warn "else, dies with the phone. That is the common way this layer fails."
printf '\n'
step "For each load-bearing account, open its vault item and confirm it holds"
step "  the TOTP seed and the printed recovery codes."
step "Registrar and Cloudflare first — losing the domain loses everything"
step "  downstream of it, including the docs site the successor is reading."
printf '\n'
note "Answer yes or no. Do not type a seed or a code anywhere in this wizard."
printf '\n'
for acct in "Registrar" "Cloudflare" "GitHub" "TorBox" "Backup storage" "Bitwarden"; do
  a=""
  ask a "$acct — item carries TOTP seed + recovery codes? (yes / no / n-a):"
  record "2FA material: $acct" "${a:-unanswered}"
  if [[ "$a" =~ ^[Nn]o ]]; then
    OUTSTANDING+=("$acct: no recovery codes on the vault item")
  fi
done

# ── 7. The index note: one row per load-bearing account ───────────────────
stage "The index note: one row per load-bearing account"
say "The orientation document a successor reads first. Written for a"
say "non-technical reader who has never logged into any of this."
printf '\n'
warn "Disposition is the one judgement no successor can make for you: cancel,"
warn "transfer, or leave running. Left blank, a grieving person guesses — and"
warn "the safe-feeling guess, cancel everything, is the one that destroys the"
warn "backups before anyone has decided whether they mattered."
printf '\n'
note "This builds the note's text into a file you'll paste into the vault next"
note "stage. Keep the answers plain: no jargon survives contact with a reader"
note "who has never heard of Proxmox."
printf '\n'

{
  printf '# Start here\n\n'
  printf 'If you are reading this, you have taken over my Bitwarden vault.\n\n'
  printf 'This is a list of the accounts that keep my home server, my website\n'
  printf 'domain and my backups alive. It tells you what each one is and what I\n'
  printf 'want done with it. You do not need to understand the server itself.\n'
  printf 'You do not have to rebuild anything — ever. Keeping it running or\n'
  printf 'turning it off are both correct answers.\n\n'
  printf 'The logins for everything below are in this same vault.\n\n'
  printf '| Account | What it is | What it costs | What I want done |\n'
  printf '| --- | --- | --- | --- |\n'
} > "$INDEX_NOTE"

for acct in "Registrar" "Cloudflare" "GitHub" "TorBox" "Backup storage" "Bitwarden"; do
  what=""; cost=""; disp=""
  printf '\n  %s%s%s\n' "$BOLD" "$acct" "$RESET"
  ask what "  In one plain sentence, what is it?"
  ask cost "  What does it cost, and how often?"
  ask disp "  Disposition (cancel / transfer / leave running):"
  printf '| %s | %s | %s | %s |\n' \
    "$acct" "${what:-—}" "${cost:-—}" "${disp:-UNDECIDED}" >> "$INDEX_NOTE"
  if [[ -z "$disp" ]]; then OUTSTANDING+=("$acct has no disposition recorded"); fi
done

{
  printf '\n## The one thing to be careful with\n\n'
  printf 'Do not cancel the backup storage until you are sure nobody wants what\n'
  printf 'is in it. Everything else can be turned off and turned back on. That\n'
  printf 'one cannot.\n\n'
  printf '## If you want to keep it running\n\n'
  printf 'The instructions are public, at the documentation site. You do not\n'
  printf 'need anything from this vault to read them.\n\n'
  printf '## Who has keys to the house\n\n'
  printf 'That list is a separate item in this vault. It is deliberately not\n'
  printf 'written down anywhere public.\n'
} >> "$INDEX_NOTE"

printf '\n'
record "Index note drafted" "$INDEX_NOTE"
say "Drafted. Read it over before you file it:"
note "  $INDEX_NOTE"
printf '\n'
pause "Press Enter when you've read it."

# ── 8. File the index note in the vault ───────────────────────────────────
stage "File the index note in the vault"
say "It has to be the first thing a successor sees, in the individual vault,"
say "not in an organization — the same rule as stage 5, and the item it would"
say "be most embarrassing to get wrong."
printf '\n'
step "New item → Secure note. Paste the contents of:"
note "    $INDEX_NOTE"
step "Title it so it sorts to the top and reads as an instruction. Something"
step "  like:  'AAA — START HERE if I have died'"
step "Confirm the item's owner is you, not an organization."
printf '\n'
open_url "https://vault.bitwarden.com/#/vault"
printf '\n'
NOTE_TITLE=""
ask NOTE_TITLE "Exact title you gave the note (copy it character for character):"
record "Index note title" "${NOTE_TITLE:-unanswered}"
if [[ -n "$NOTE_TITLE" ]]; then write_env INDEX_NOTE_TITLE "$NOTE_TITLE"; fi
if [[ -z "$NOTE_TITLE" ]]; then
  OUTSTANDING+=("Index note not filed in the vault")
fi
warn "Delete the draft once it's in the vault: rm $INDEX_NOTE"

# ── 9. The envelope ───────────────────────────────────────────────────────
stage "The envelope"
say "The sealed escrow with your trust paperwork. Roots only: credentials that"
say "unlock other credentials and never rotate."
printf '\n'
note "It is the backstop for the case Emergency Access cannot cover — the"
note "request denied by mistake, the contact who lost their own account,"
note "Bitwarden itself unreachable. Belt and braces, deliberately."
printf '\n'
step "Open it. Confirm it holds the Bitwarden Emergency Kit: master password"
step "  and its two-step recovery code."
step "Add one line naming the index note by its exact title:"
if [[ -n "$NOTE_TITLE" ]]; then
  printf '\n      %s%s%s\n\n' "$BOLD" "In the vault, read the note called \"$NOTE_TITLE\" first." "$RESET"
else
  printf '\n      %s%s%s\n\n' "$BOLD" "In the vault, read the note titled <exact title> first." "$RESET"
fi
step "Reseal it and put it back with the trust paperwork."
printf '\n'
warn "The backup encryption key belongs in here too, and does not exist yet."
warn "It gets added when the backup architecture lands. docs/secrets.md tracks"
warn "it as pending; it is not a gap in this ticket."
printf '\n'
tick "Envelope verified and pointer line added" \
     "Does the envelope hold the Emergency Kit AND point at the index note?"

# ── 10. The conversation ──────────────────────────────────────────────────
stage "The conversation"
say "The last step, and the one most likely to be skipped. An emergency"
say "contact who does not know they are one, or does not know what the vault"
say "is for, will not use it."
printf '\n'
say "Roughly what to say — it takes two minutes:"
printf '\n'
note "  'I've set you up as an emergency contact on my password manager."
note "   If I die, you request access, and after 30 days it opens."
note "   Inside there's a note at the top called \"${NOTE_TITLE:-START HERE}\"."
note "   It lists the handful of accounts that run the house's computer stuff"
note "   and says what I want done with each one. You don't have to understand"
note "   any of it, and you never have to rebuild anything. Turning it all off"
note "   is a fine answer — the note says which one thing not to delete."
note "   There's also a sealed envelope with the trust paperwork as a backup."
note "   Accept the email invitation when it arrives, and I'll phone you to"
note "   read out a verification phrase.'"
printf '\n'
warn "The 30-day wait only starts when they request access. Someone who does"
warn "not know the vault exists never starts the clock."
printf '\n'
tick "Both brothers told what the vault is for" \
     "Have you actually had this conversation with everyone you invited?"

# ──────────────────────────────────────────────────────────────────────────

_clear
printf '\n%s%s  ✓ Succession layer run complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
if (( ${#OUTSTANDING[@]} )); then
  warn "NOT done — the succession layer is not standing until these are:"
  for o in "${OUTSTANDING[@]}"; do note "  - $o"; done
  printf '\n'
  {
    report_header "Outstanding at end of run"
    for o in "${OUTSTANDING[@]}"; do printf -- '- %s\n' "$o"; done
  } >> "$REPORT"
  note "Re-run this wizard once they're cleared; it remembers your answers."
else
  say "Every box ticked. Issue #20 can be resolved."
fi
printf '\n'
note "Report: $REPORT"
if (( ${#WRITTEN_ENV[@]} )); then note "Remembered for a re-run: $ENV_FILE"; fi
printf '\n'
warn "Skim the report before posting it. Email addresses and a renewal date are"
warn "in there; issue #20 is on a PUBLIC repository. No credential can be — the"
warn "wizard never asked for one."
printf '\n'
say "Send it back with whichever is easiest:"
note "  cat $REPORT                                # then copy-paste"
note "  gh issue comment 20 --body-file $REPORT    # straight onto the ticket"
printf '\n'
